name: Generate Pac-Man Contribution Graph

on:
  schedule: # Runs once a day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows you to run it manually

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Pac-Man Graph
        uses: Platane/snk@v3
        with:
          github_user_name: kiran-8287
          outputs: |
            pacman-contribution-graph.svg
            pacman-contribution-graph-dark.svg

      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: .
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
